description: Squash all branches


inputs:
  depth:
    description: Squash amount
    required: false
    default: 0

  author:
    description: Squash author
    required: false
    default: ''


runs:
  using: composite

  steps:
    - shell: bash
      run: |
        branches=()
        eval "$(git for-each-ref --shell --format='branches+=(%(refname:lstrip=3))' 'refs/remotes/origin')"

        git for-each-ref --shell 'refs/remotes/origin'


        for branch in "${branches[@]}"; do
          if [[ "$branch" == "HEAD" ]]; then
            continue
          fi


          if [[ -z "${{ inputs.author }}" ]]; then
            author=$(git config user.name)
          else
            author=${{ inputs.author }}
          fi


          git checkout $branch --quiet


          #####


          depth=${{ inputs.depth }}


          if (( $depth == 0 )); then
            git fetch --deepen=500 --quiet
            max_merge=$(git rev-list --count HEAD)


            while (( $depth < $max_merge )); do
              if [[ "$(git log -1 --skip=$depth --pretty=format:'%an')" != "$author" ]]; then
                break
              fi

              depth=$(( $depth+1 ))
            done

          else
            git fetch --deepen=$depth --quiet
            max_merge=$(git rev-list --count HEAD)


            if (( $depth > $max_merge )); then
              depth=$max_merge
            fi
          fi


          #####


          if (( $depth >= 2 )); then
            git reset --soft HEAD~$(( $depth-1 ))
            git commit --amend --no-edit

            git push -f origin HEAD:$branch
          fi
        done
