description: Runs schedule


inputs:
  token:
    description: Personal Access Token
    required: false
    default: ${{ github.token }}


runs:
  using: composite

  steps:
    - uses: li5ht4ay-3es/ac5io4s@user-action


    - uses: li5ht4ay-3es/ac5io4s@checkout-branch
      with:
        token: ${{ inputs.token }}


    - uses: li5ht4ay-3es/ac5io4s@keep-alive
